title: سایت آموزشی خانم داورپناه
description: آموزش ریاضی عمومی ۱
baseurl: ""
url: "https://maryamdavarpanah124-bot.github.io"

collections:
  notes:
    output: true
    permalink: /notes/:name.html
